# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[[main]]
name = "Accueil"
url = "#hero"
weight = 100

[[main]]
name = "Organisation"
url = "#organisation"
weight = 200

[[main]]
identifier = "newateliers"
name = "Futurs ateliers"
url = "#upcoming_workshops"
weight = 300

[[main]]
identifier = "oldateliers"
name = "Ateliers passés"
url = "#past_workshops"
weight = 400

[[main]]
name = "Camps d'été"
url = "#bootcamp"
weight = 500

[[main]]
name = "À propos"
url = "#about"
weight = 600

