---
title: Atelier découverte LearnR
author: ~
date: '2017-09-25'
slug: learnr
categories: ["R"]
tags: ["workshop", "package", "teachings"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- ## courriel -->

<!-- Pour learnR je dirai que c’est un outil intéressant pour réaliser des TP structurés selon une trame précise et pour lesquels on souhaite modifier les données. -->

<!-- Par contre, il me faudrait plus de temps pour voir comment exporter/sauvegarder les codes et sorties R dans un fichier (.R par exemple). -->

<!-- ### Jessica -->

<!-- avec Marie qui était sansordi, nous avons regardé le tuto de learnR et en particulier les différentes fonctionnalités qui pourraient permettre de récupérer les réponses des étudiants... On a conclu que c'était plus du Shiny que du learnR. -->

<!-- On a vu les options -->

<!-- 3- sur la fonction `quiz( )`, on a cherché à ne pas faire apparaître de réponse et on a été surprises de voir qu'en recompilant on voit encore ce qu'on a répondu avant... -->

<!-- Bref, ça n'a pas été très productif selon moi (même si ma machine a bien voulu faire ce que je demandais !) et ça a donné l'impression qu'on faisait tous un peu la même chose, il faudrait peut être décider en début d'HappyR qui regarde quoi et se mettre en petits groupes pour traiter chacun une question spécifique, disons en 1h et préparer sur place une courte restitution aux autres (ce qui éviterait aussi la compilation de nos différents retours). C'est peut être un peu utopique de se dire que c'est faisable sans que personne n'est déjà regardé plus en détails avant qu'on se retrouve...  -->

<!-- De mon côté, j'avais regardé rapidement quelles étaient les possibilités de générer des sujets différents et j'ai trouvé un exemple de publipostage "Mail merge" qui peut permettre  de faire cela (au moins si 'l'on souhaite juste générer N sujets au format PDF par exemple - ensuite il faut combiner avec du learnR et du Shiny si on veut aller jusqu'à récupérer les réponses pour une notation d'évaluation automatisée), cf pour ceux qui ça intéresse https://www.r-bloggers.com/mail-merge-with-rmarkdown/. -->

<!-- bonne compil' et merci de t'en charger -->

<!-- Jessica TRESSOU -->



<!-- ### Isabelle -->

<!-- Impressions sur learnR : outil sympathique quand on veut poser des questions via une interface WEB à des personnes. Mais se pose crucialement la question comment récupérer les réponses. -->

<!-- Merci pour cette initiative de StateoftheR qui va peut-être me permettre de pas trop perdre la main ou plutôt de raccrocher. Par contre, je ne pourrais pas être là le 20/10. Désolée. Réunion experts Anses oblige. -->



<!-- ### Maud -->

<!-- - le package produit des supports plus adaptés à des interventions de type tutoriel ou des auto-évaluations -->
<!-- - inconvénients liés à l'indépendance des chunks; nécessite d'ajouter des lignes de code dans le setup ou de faire des liens entre chunks (mais comment?) -->

### Vue d'ensemble

Le package  `learnr` permet de créer des tutoriels (voir le [site dédié](https://rstudio.github.io/learnr/) ou [le blog de présentation](https://blog.rstudio.com/2017/07/11/introducing-learnr/)). Les tutoriels incluent du texte, des champs pour taper et exécuter des commandes `R` (pouvant être pré-formatés) et des questionnaires à choix multiples. 
Les champs peuvent inclure des indices à afficher pour l'utilisateur ou des solutions. 
Pour fonctionner, le document créé au format Rmarkdown doit être envoyé sur un serveur shiny. Il est alors
nécessaire de créér un compte sur [shinyapp](https://www.shinyapps.io/).

Avec uniquement le package `learnr`, il est uniquement possible de vérifier que les réponses données aux questions à choix multiples sont les bonnes. Par contre, il n'est pas possible de vérifier les commandes `R` tapées ni leur résultat. 
Un package [checkr](https://github.com/dtkaplan/checkr) disponible sur github doit permettre de faire ces vérifications.

### Limitations

Des essais menés, il a été conclu que `learnr` est un package intéressant mais qui ne permettra pas forcément de faire un TP complet de statistique sous R.
Toutefois, il  peut être employé pour :

- présenter certaines fonctions centrales en R en détaillant les différentes options et fournir des exemples à des étudiants en TP, 

- faire une vignette d'un package développé sous R,

- proposer des auto-évaluations pour les étudiants.

Nous nous sommes heurtés à certaines limites :

- il n'est pas possible de récupérer les commandes tapées dans les champs `R` par l'utilisateur ni les résultats correspondants. Ainsi un étudiant n'aura aucune trace de son travail si cet outil est employé pour le faire travailler en TP.

- il n'est pas possible de récupérer les commandes tapées dans les champs `R` ni les réponses aux questions à choix multiples afin de les centraliser et de s'en servir à des fins d'évaluations.

- les "chunks" (environnement permettant de créer des champs `R`) sont indépendants les uns des autres donc il est difficile de construire une progressivité dans un travail avec `learnr`. On peut définir au début dans un chunk `setup`, 
un environnement général qui sera commun à tous les champs `R`. On peut également pour chaque chunk ajouter un chunk du même nom auquel on ajoute `-setup` pour définir un environnement propre au champ correspondant.

- le document `learnr` étant hébergé sur un serveur, l'importation des données ne peut pas être présentée de manière classique en local. Les données doivent être chargées à partir d'une adresse web.

### Quelques astuces utiles :

  1- `exercise.timelimit = 10` permet de limiter le temps de réponses, `exercise.lines = 5` pour définir le nombre de lignes de console permettant de répondre.

  2- il n'est pas possible de mettre à la fois `solution` et `hint`(en créant un nouveau chunk portant le même nom suivi de `-hint` ou `-solution` selon le cas ). Si on le fait, la solution devient le `next hint`. On peut aussi mettre plusieurs `hint` en ajoutant `-1`, `-2` pour les ordonner. 


